"""added id column

Revision ID: df0d94f22597
Revises: fae19f25820b
Create Date: 2021-03-18 00:14:06.691728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0d94f22597'
down_revision = 'fae19f25820b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')

    op.create_table('user',
    sa.Column('id', sa.Integer, nullable=False, autoincrement=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')

  
    op.create_table('user',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###
